// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace DiagnosticApp_API
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"sym1")]
            public float Sym1 { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"sym2")]
            public float Sym2 { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"sym3")]
            public float Sym3 { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"sym4")]
            public float Sym4 { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"sym5")]
            public float Sym5 { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"sym6")]
            public float Sym6 { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"sym7")]
            public float Sym7 { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"sym8")]
            public float Sym8 { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"sym9")]
            public float Sym9 { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"sym10")]
            public float Sym10 { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"sym11")]
            public float Sym11 { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"sym12")]
            public float Sym12 { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"sym13")]
            public float Sym13 { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"sym14")]
            public float Sym14 { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"sym15")]
            public float Sym15 { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"sym16")]
            public float Sym16 { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"sym17")]
            public float Sym17 { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"sym18")]
            public float Sym18 { get; set; }

            [LoadColumn(18)]
            [ColumnName(@"sym19")]
            public float Sym19 { get; set; }

            [LoadColumn(19)]
            [ColumnName(@"sym20")]
            public float Sym20 { get; set; }

            [LoadColumn(20)]
            [ColumnName(@"sym21")]
            public float Sym21 { get; set; }

            [LoadColumn(21)]
            [ColumnName(@"sym22")]
            public float Sym22 { get; set; }

            [LoadColumn(22)]
            [ColumnName(@"sym23")]
            public float Sym23 { get; set; }

            [LoadColumn(23)]
            [ColumnName(@"sym24")]
            public float Sym24 { get; set; }

            [LoadColumn(24)]
            [ColumnName(@"sym25")]
            public float Sym25 { get; set; }

            [LoadColumn(25)]
            [ColumnName(@"sym26")]
            public float Sym26 { get; set; }

            [LoadColumn(26)]
            [ColumnName(@"sym27")]
            public float Sym27 { get; set; }

            [LoadColumn(27)]
            [ColumnName(@"sym28")]
            public float Sym28 { get; set; }

            [LoadColumn(28)]
            [ColumnName(@"sym29")]
            public float Sym29 { get; set; }

            [LoadColumn(29)]
            [ColumnName(@"sym30")]
            public float Sym30 { get; set; }

            [LoadColumn(30)]
            [ColumnName(@"sym31")]
            public float Sym31 { get; set; }

            [LoadColumn(31)]
            [ColumnName(@"sym32")]
            public float Sym32 { get; set; }

            [LoadColumn(32)]
            [ColumnName(@"sym33")]
            public float Sym33 { get; set; }

            [LoadColumn(33)]
            [ColumnName(@"sym34")]
            public float Sym34 { get; set; }

            [LoadColumn(34)]
            [ColumnName(@"sym35")]
            public float Sym35 { get; set; }

            [LoadColumn(35)]
            [ColumnName(@"sym36")]
            public float Sym36 { get; set; }

            [LoadColumn(36)]
            [ColumnName(@"sym37")]
            public float Sym37 { get; set; }

            [LoadColumn(37)]
            [ColumnName(@"sym38")]
            public float Sym38 { get; set; }

            [LoadColumn(38)]
            [ColumnName(@"sym39")]
            public float Sym39 { get; set; }

            [LoadColumn(39)]
            [ColumnName(@"sym40")]
            public float Sym40 { get; set; }

            [LoadColumn(40)]
            [ColumnName(@"sym41")]
            public float Sym41 { get; set; }

            [LoadColumn(41)]
            [ColumnName(@"sym42")]
            public float Sym42 { get; set; }

            [LoadColumn(42)]
            [ColumnName(@"sym43")]
            public float Sym43 { get; set; }

            [LoadColumn(43)]
            [ColumnName(@"sym44")]
            public float Sym44 { get; set; }

            [LoadColumn(44)]
            [ColumnName(@"sym45")]
            public float Sym45 { get; set; }

            [LoadColumn(45)]
            [ColumnName(@"sym46")]
            public float Sym46 { get; set; }

            [LoadColumn(46)]
            [ColumnName(@"sym47")]
            public float Sym47 { get; set; }

            [LoadColumn(47)]
            [ColumnName(@"sym48")]
            public float Sym48 { get; set; }

            [LoadColumn(48)]
            [ColumnName(@"sym49")]
            public float Sym49 { get; set; }

            [LoadColumn(49)]
            [ColumnName(@"sym50")]
            public float Sym50 { get; set; }

            [LoadColumn(50)]
            [ColumnName(@"sym51")]
            public float Sym51 { get; set; }

            [LoadColumn(51)]
            [ColumnName(@"sym52")]
            public float Sym52 { get; set; }

            [LoadColumn(52)]
            [ColumnName(@"sym53")]
            public float Sym53 { get; set; }

            [LoadColumn(53)]
            [ColumnName(@"sym54")]
            public float Sym54 { get; set; }

            [LoadColumn(54)]
            [ColumnName(@"sym55")]
            public float Sym55 { get; set; }

            [LoadColumn(55)]
            [ColumnName(@"sym56")]
            public float Sym56 { get; set; }

            [LoadColumn(56)]
            [ColumnName(@"sym57")]
            public float Sym57 { get; set; }

            [LoadColumn(57)]
            [ColumnName(@"sym58")]
            public float Sym58 { get; set; }

            [LoadColumn(58)]
            [ColumnName(@"sym59")]
            public float Sym59 { get; set; }

            [LoadColumn(59)]
            [ColumnName(@"sym60")]
            public float Sym60 { get; set; }

            [LoadColumn(60)]
            [ColumnName(@"sym61")]
            public float Sym61 { get; set; }

            [LoadColumn(61)]
            [ColumnName(@"sym62")]
            public float Sym62 { get; set; }

            [LoadColumn(62)]
            [ColumnName(@"sym63")]
            public float Sym63 { get; set; }

            [LoadColumn(63)]
            [ColumnName(@"sym64")]
            public float Sym64 { get; set; }

            [LoadColumn(64)]
            [ColumnName(@"sym65")]
            public float Sym65 { get; set; }

            [LoadColumn(65)]
            [ColumnName(@"sym66")]
            public float Sym66 { get; set; }

            [LoadColumn(66)]
            [ColumnName(@"sym67")]
            public float Sym67 { get; set; }

            [LoadColumn(67)]
            [ColumnName(@"sym68")]
            public float Sym68 { get; set; }

            [LoadColumn(68)]
            [ColumnName(@"sym69")]
            public float Sym69 { get; set; }

            [LoadColumn(69)]
            [ColumnName(@"sym70")]
            public float Sym70 { get; set; }

            [LoadColumn(70)]
            [ColumnName(@"sym71")]
            public float Sym71 { get; set; }

            [LoadColumn(71)]
            [ColumnName(@"sym72")]
            public float Sym72 { get; set; }

            [LoadColumn(72)]
            [ColumnName(@"sym73")]
            public float Sym73 { get; set; }

            [LoadColumn(73)]
            [ColumnName(@"sym74")]
            public float Sym74 { get; set; }

            [LoadColumn(74)]
            [ColumnName(@"sym75")]
            public float Sym75 { get; set; }

            [LoadColumn(75)]
            [ColumnName(@"sym76")]
            public float Sym76 { get; set; }

            [LoadColumn(76)]
            [ColumnName(@"sym77")]
            public float Sym77 { get; set; }

            [LoadColumn(77)]
            [ColumnName(@"sym78")]
            public float Sym78 { get; set; }

            [LoadColumn(78)]
            [ColumnName(@"sym79")]
            public float Sym79 { get; set; }

            [LoadColumn(79)]
            [ColumnName(@"sym80")]
            public float Sym80 { get; set; }

            [LoadColumn(80)]
            [ColumnName(@"sym81")]
            public float Sym81 { get; set; }

            [LoadColumn(81)]
            [ColumnName(@"sym82")]
            public float Sym82 { get; set; }

            [LoadColumn(82)]
            [ColumnName(@"sym83")]
            public float Sym83 { get; set; }

            [LoadColumn(83)]
            [ColumnName(@"sym84")]
            public float Sym84 { get; set; }

            [LoadColumn(84)]
            [ColumnName(@"sym85")]
            public float Sym85 { get; set; }

            [LoadColumn(85)]
            [ColumnName(@"sym86")]
            public float Sym86 { get; set; }

            [LoadColumn(86)]
            [ColumnName(@"sym87")]
            public float Sym87 { get; set; }

            [LoadColumn(87)]
            [ColumnName(@"sym88")]
            public float Sym88 { get; set; }

            [LoadColumn(88)]
            [ColumnName(@"sym89")]
            public float Sym89 { get; set; }

            [LoadColumn(89)]
            [ColumnName(@"sym90")]
            public float Sym90 { get; set; }

            [LoadColumn(90)]
            [ColumnName(@"sym91")]
            public float Sym91 { get; set; }

            [LoadColumn(91)]
            [ColumnName(@"sym92")]
            public float Sym92 { get; set; }

            [LoadColumn(92)]
            [ColumnName(@"sym93")]
            public float Sym93 { get; set; }

            [LoadColumn(93)]
            [ColumnName(@"sym94")]
            public float Sym94 { get; set; }

            [LoadColumn(94)]
            [ColumnName(@"sym95")]
            public float Sym95 { get; set; }

            [LoadColumn(95)]
            [ColumnName(@"sym96")]
            public float Sym96 { get; set; }

            [LoadColumn(96)]
            [ColumnName(@"sym97")]
            public float Sym97 { get; set; }

            [LoadColumn(97)]
            [ColumnName(@"sym98")]
            public float Sym98 { get; set; }

            [LoadColumn(98)]
            [ColumnName(@"sym99")]
            public float Sym99 { get; set; }

            [LoadColumn(99)]
            [ColumnName(@"sym100")]
            public float Sym100 { get; set; }

            [LoadColumn(100)]
            [ColumnName(@"sym101")]
            public float Sym101 { get; set; }

            [LoadColumn(101)]
            [ColumnName(@"sym102")]
            public float Sym102 { get; set; }

            [LoadColumn(102)]
            [ColumnName(@"sym103")]
            public float Sym103 { get; set; }

            [LoadColumn(103)]
            [ColumnName(@"sym104")]
            public float Sym104 { get; set; }

            [LoadColumn(104)]
            [ColumnName(@"sym105")]
            public float Sym105 { get; set; }

            [LoadColumn(105)]
            [ColumnName(@"sym106")]
            public float Sym106 { get; set; }

            [LoadColumn(106)]
            [ColumnName(@"sym107")]
            public float Sym107 { get; set; }

            [LoadColumn(107)]
            [ColumnName(@"sym108")]
            public float Sym108 { get; set; }

            [LoadColumn(108)]
            [ColumnName(@"sym109")]
            public float Sym109 { get; set; }

            [LoadColumn(109)]
            [ColumnName(@"sym110")]
            public float Sym110 { get; set; }

            [LoadColumn(110)]
            [ColumnName(@"sym111")]
            public float Sym111 { get; set; }

            [LoadColumn(111)]
            [ColumnName(@"sym112")]
            public float Sym112 { get; set; }

            [LoadColumn(112)]
            [ColumnName(@"sym113")]
            public float Sym113 { get; set; }

            [LoadColumn(113)]
            [ColumnName(@"sym114")]
            public float Sym114 { get; set; }

            [LoadColumn(114)]
            [ColumnName(@"sym115")]
            public float Sym115 { get; set; }

            [LoadColumn(115)]
            [ColumnName(@"sym116")]
            public float Sym116 { get; set; }

            [LoadColumn(116)]
            [ColumnName(@"sym117")]
            public float Sym117 { get; set; }

            [LoadColumn(117)]
            [ColumnName(@"sym118")]
            public float Sym118 { get; set; }

            [LoadColumn(118)]
            [ColumnName(@"sym119")]
            public float Sym119 { get; set; }

            [LoadColumn(119)]
            [ColumnName(@"sym120")]
            public float Sym120 { get; set; }

            [LoadColumn(120)]
            [ColumnName(@"sym121")]
            public float Sym121 { get; set; }

            [LoadColumn(121)]
            [ColumnName(@"sym122")]
            public float Sym122 { get; set; }

            [LoadColumn(122)]
            [ColumnName(@"sym123")]
            public float Sym123 { get; set; }

            [LoadColumn(123)]
            [ColumnName(@"sym124")]
            public float Sym124 { get; set; }

            [LoadColumn(124)]
            [ColumnName(@"sym125")]
            public float Sym125 { get; set; }

            [LoadColumn(125)]
            [ColumnName(@"sym126")]
            public float Sym126 { get; set; }

            [LoadColumn(126)]
            [ColumnName(@"sym127")]
            public float Sym127 { get; set; }

            [LoadColumn(127)]
            [ColumnName(@"sym128")]
            public float Sym128 { get; set; }

            [LoadColumn(128)]
            [ColumnName(@"sym129")]
            public float Sym129 { get; set; }

            [LoadColumn(129)]
            [ColumnName(@"sym130")]
            public float Sym130 { get; set; }

            [LoadColumn(130)]
            [ColumnName(@"sym131")]
            public float Sym131 { get; set; }

            [LoadColumn(131)]
            [ColumnName(@"sym132")]
            public float Sym132 { get; set; }

            [LoadColumn(132)]
            [ColumnName(@"sym133")]
            public float Sym133 { get; set; }

            [LoadColumn(133)]
            [ColumnName(@"sym134")]
            public float Sym134 { get; set; }

            [LoadColumn(134)]
            [ColumnName(@"sym135")]
            public float Sym135 { get; set; }

            [LoadColumn(135)]
            [ColumnName(@"sym136")]
            public float Sym136 { get; set; }

            [LoadColumn(136)]
            [ColumnName(@"sym137")]
            public float Sym137 { get; set; }

            [LoadColumn(137)]
            [ColumnName(@"sym138")]
            public float Sym138 { get; set; }

            [LoadColumn(138)]
            [ColumnName(@"sym139")]
            public float Sym139 { get; set; }

            [LoadColumn(139)]
            [ColumnName(@"sym140")]
            public float Sym140 { get; set; }

            [LoadColumn(140)]
            [ColumnName(@"sym141")]
            public float Sym141 { get; set; }

            [LoadColumn(141)]
            [ColumnName(@"sym142")]
            public float Sym142 { get; set; }

            [LoadColumn(142)]
            [ColumnName(@"sym143")]
            public float Sym143 { get; set; }

            [LoadColumn(143)]
            [ColumnName(@"sym144")]
            public float Sym144 { get; set; }

            [LoadColumn(144)]
            [ColumnName(@"sym145")]
            public float Sym145 { get; set; }

            [LoadColumn(145)]
            [ColumnName(@"sym146")]
            public float Sym146 { get; set; }

            [LoadColumn(146)]
            [ColumnName(@"sym147")]
            public float Sym147 { get; set; }

            [LoadColumn(147)]
            [ColumnName(@"sym148")]
            public float Sym148 { get; set; }

            [LoadColumn(148)]
            [ColumnName(@"sym149")]
            public float Sym149 { get; set; }

            [LoadColumn(149)]
            [ColumnName(@"sym150")]
            public float Sym150 { get; set; }

            [LoadColumn(150)]
            [ColumnName(@"sym151")]
            public float Sym151 { get; set; }

            [LoadColumn(151)]
            [ColumnName(@"sym152")]
            public float Sym152 { get; set; }

            [LoadColumn(152)]
            [ColumnName(@"sym153")]
            public float Sym153 { get; set; }

            [LoadColumn(153)]
            [ColumnName(@"sym154")]
            public float Sym154 { get; set; }

            [LoadColumn(154)]
            [ColumnName(@"sym155")]
            public float Sym155 { get; set; }

            [LoadColumn(155)]
            [ColumnName(@"sym156")]
            public float Sym156 { get; set; }

            [LoadColumn(156)]
            [ColumnName(@"sym157")]
            public float Sym157 { get; set; }

            [LoadColumn(157)]
            [ColumnName(@"sym158")]
            public float Sym158 { get; set; }

            [LoadColumn(158)]
            [ColumnName(@"sym159")]
            public float Sym159 { get; set; }

            [LoadColumn(159)]
            [ColumnName(@"sym160")]
            public float Sym160 { get; set; }

            [LoadColumn(160)]
            [ColumnName(@"sym161")]
            public float Sym161 { get; set; }

            [LoadColumn(161)]
            [ColumnName(@"sym162")]
            public float Sym162 { get; set; }

            [LoadColumn(162)]
            [ColumnName(@"sym163")]
            public float Sym163 { get; set; }

            [LoadColumn(163)]
            [ColumnName(@"sym164")]
            public float Sym164 { get; set; }

            [LoadColumn(164)]
            [ColumnName(@"sym165")]
            public float Sym165 { get; set; }

            [LoadColumn(165)]
            [ColumnName(@"sym166")]
            public float Sym166 { get; set; }

            [LoadColumn(166)]
            [ColumnName(@"sym167")]
            public float Sym167 { get; set; }

            [LoadColumn(167)]
            [ColumnName(@"sym168")]
            public float Sym168 { get; set; }

            [LoadColumn(168)]
            [ColumnName(@"sym169")]
            public float Sym169 { get; set; }

            [LoadColumn(169)]
            [ColumnName(@"sym170")]
            public float Sym170 { get; set; }

            [LoadColumn(170)]
            [ColumnName(@"sym171")]
            public float Sym171 { get; set; }

            [LoadColumn(171)]
            [ColumnName(@"sym172")]
            public float Sym172 { get; set; }

            [LoadColumn(172)]
            [ColumnName(@"sym173")]
            public float Sym173 { get; set; }

            [LoadColumn(173)]
            [ColumnName(@"sym174")]
            public float Sym174 { get; set; }

            [LoadColumn(174)]
            [ColumnName(@"sym175")]
            public float Sym175 { get; set; }

            [LoadColumn(175)]
            [ColumnName(@"sym176")]
            public float Sym176 { get; set; }

            [LoadColumn(176)]
            [ColumnName(@"sym177")]
            public float Sym177 { get; set; }

            [LoadColumn(177)]
            [ColumnName(@"sym178")]
            public float Sym178 { get; set; }

            [LoadColumn(178)]
            [ColumnName(@"sym179")]
            public float Sym179 { get; set; }

            [LoadColumn(179)]
            [ColumnName(@"sym180")]
            public float Sym180 { get; set; }

            [LoadColumn(180)]
            [ColumnName(@"sym181")]
            public float Sym181 { get; set; }

            [LoadColumn(181)]
            [ColumnName(@"sym182")]
            public float Sym182 { get; set; }

            [LoadColumn(182)]
            [ColumnName(@"sym183")]
            public float Sym183 { get; set; }

            [LoadColumn(183)]
            [ColumnName(@"sym184")]
            public float Sym184 { get; set; }

            [LoadColumn(184)]
            [ColumnName(@"sym185")]
            public float Sym185 { get; set; }

            [LoadColumn(185)]
            [ColumnName(@"sym186")]
            public float Sym186 { get; set; }

            [LoadColumn(186)]
            [ColumnName(@"sym187")]
            public float Sym187 { get; set; }

            [LoadColumn(187)]
            [ColumnName(@"sym188")]
            public float Sym188 { get; set; }

            [LoadColumn(188)]
            [ColumnName(@"sym189")]
            public float Sym189 { get; set; }

            [LoadColumn(189)]
            [ColumnName(@"sym190")]
            public float Sym190 { get; set; }

            [LoadColumn(190)]
            [ColumnName(@"sym191")]
            public float Sym191 { get; set; }

            [LoadColumn(191)]
            [ColumnName(@"sym192")]
            public float Sym192 { get; set; }

            [LoadColumn(192)]
            [ColumnName(@"sym193")]
            public float Sym193 { get; set; }

            [LoadColumn(193)]
            [ColumnName(@"sym194")]
            public float Sym194 { get; set; }

            [LoadColumn(194)]
            [ColumnName(@"sym195")]
            public float Sym195 { get; set; }

            [LoadColumn(195)]
            [ColumnName(@"sym196")]
            public float Sym196 { get; set; }

            [LoadColumn(196)]
            [ColumnName(@"sym197")]
            public float Sym197 { get; set; }

            [LoadColumn(197)]
            [ColumnName(@"sym198")]
            public float Sym198 { get; set; }

            [LoadColumn(198)]
            [ColumnName(@"sym199")]
            public float Sym199 { get; set; }

            [LoadColumn(199)]
            [ColumnName(@"sym200")]
            public float Sym200 { get; set; }

            [LoadColumn(200)]
            [ColumnName(@"sym201")]
            public float Sym201 { get; set; }

            [LoadColumn(201)]
            [ColumnName(@"sym202")]
            public float Sym202 { get; set; }

            [LoadColumn(202)]
            [ColumnName(@"sym203")]
            public float Sym203 { get; set; }

            [LoadColumn(203)]
            [ColumnName(@"sym204")]
            public float Sym204 { get; set; }

            [LoadColumn(204)]
            [ColumnName(@"sym205")]
            public float Sym205 { get; set; }

            [LoadColumn(205)]
            [ColumnName(@"sym206")]
            public float Sym206 { get; set; }

            [LoadColumn(206)]
            [ColumnName(@"sym207")]
            public float Sym207 { get; set; }

            [LoadColumn(207)]
            [ColumnName(@"sym208")]
            public float Sym208 { get; set; }

            [LoadColumn(208)]
            [ColumnName(@"sym209")]
            public float Sym209 { get; set; }

            [LoadColumn(209)]
            [ColumnName(@"sym210")]
            public float Sym210 { get; set; }

            [LoadColumn(210)]
            [ColumnName(@"sym211")]
            public float Sym211 { get; set; }

            [LoadColumn(211)]
            [ColumnName(@"sym212")]
            public float Sym212 { get; set; }

            [LoadColumn(212)]
            [ColumnName(@"sym213")]
            public float Sym213 { get; set; }

            [LoadColumn(213)]
            [ColumnName(@"sym214")]
            public float Sym214 { get; set; }

            [LoadColumn(214)]
            [ColumnName(@"sym215")]
            public float Sym215 { get; set; }

            [LoadColumn(215)]
            [ColumnName(@"sym216")]
            public float Sym216 { get; set; }

            [LoadColumn(216)]
            [ColumnName(@"sym217")]
            public float Sym217 { get; set; }

            [LoadColumn(217)]
            [ColumnName(@"sym218")]
            public float Sym218 { get; set; }

            [LoadColumn(218)]
            [ColumnName(@"sym219")]
            public float Sym219 { get; set; }

            [LoadColumn(219)]
            [ColumnName(@"sym220")]
            public float Sym220 { get; set; }

            [LoadColumn(220)]
            [ColumnName(@"sym221")]
            public float Sym221 { get; set; }

            [LoadColumn(221)]
            [ColumnName(@"sym222")]
            public float Sym222 { get; set; }

            [LoadColumn(222)]
            [ColumnName(@"sym223")]
            public float Sym223 { get; set; }

            [LoadColumn(223)]
            [ColumnName(@"sym224")]
            public float Sym224 { get; set; }

            [LoadColumn(224)]
            [ColumnName(@"sym225")]
            public float Sym225 { get; set; }

            [LoadColumn(225)]
            [ColumnName(@"sym226")]
            public float Sym226 { get; set; }

            [LoadColumn(227)]
            [ColumnName(@"Disease")]
            public float Disease { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"sym1")]
            public float Sym1 { get; set; }

            [ColumnName(@"sym2")]
            public float Sym2 { get; set; }

            [ColumnName(@"sym3")]
            public float Sym3 { get; set; }

            [ColumnName(@"sym4")]
            public float Sym4 { get; set; }

            [ColumnName(@"sym5")]
            public float Sym5 { get; set; }

            [ColumnName(@"sym6")]
            public float Sym6 { get; set; }

            [ColumnName(@"sym7")]
            public float Sym7 { get; set; }

            [ColumnName(@"sym8")]
            public float Sym8 { get; set; }

            [ColumnName(@"sym9")]
            public float Sym9 { get; set; }

            [ColumnName(@"sym10")]
            public float Sym10 { get; set; }

            [ColumnName(@"sym11")]
            public float Sym11 { get; set; }

            [ColumnName(@"sym12")]
            public float Sym12 { get; set; }

            [ColumnName(@"sym13")]
            public float Sym13 { get; set; }

            [ColumnName(@"sym14")]
            public float Sym14 { get; set; }

            [ColumnName(@"sym15")]
            public float Sym15 { get; set; }

            [ColumnName(@"sym16")]
            public float Sym16 { get; set; }

            [ColumnName(@"sym17")]
            public float Sym17 { get; set; }

            [ColumnName(@"sym18")]
            public float Sym18 { get; set; }

            [ColumnName(@"sym19")]
            public float Sym19 { get; set; }

            [ColumnName(@"sym20")]
            public float Sym20 { get; set; }

            [ColumnName(@"sym21")]
            public float Sym21 { get; set; }

            [ColumnName(@"sym22")]
            public float Sym22 { get; set; }

            [ColumnName(@"sym23")]
            public float Sym23 { get; set; }

            [ColumnName(@"sym24")]
            public float Sym24 { get; set; }

            [ColumnName(@"sym25")]
            public float Sym25 { get; set; }

            [ColumnName(@"sym26")]
            public float Sym26 { get; set; }

            [ColumnName(@"sym27")]
            public float Sym27 { get; set; }

            [ColumnName(@"sym28")]
            public float Sym28 { get; set; }

            [ColumnName(@"sym29")]
            public float Sym29 { get; set; }

            [ColumnName(@"sym30")]
            public float Sym30 { get; set; }

            [ColumnName(@"sym31")]
            public float Sym31 { get; set; }

            [ColumnName(@"sym32")]
            public float Sym32 { get; set; }

            [ColumnName(@"sym33")]
            public float Sym33 { get; set; }

            [ColumnName(@"sym34")]
            public float Sym34 { get; set; }

            [ColumnName(@"sym35")]
            public float Sym35 { get; set; }

            [ColumnName(@"sym36")]
            public float Sym36 { get; set; }

            [ColumnName(@"sym37")]
            public float Sym37 { get; set; }

            [ColumnName(@"sym38")]
            public float Sym38 { get; set; }

            [ColumnName(@"sym39")]
            public float Sym39 { get; set; }

            [ColumnName(@"sym40")]
            public float Sym40 { get; set; }

            [ColumnName(@"sym41")]
            public float Sym41 { get; set; }

            [ColumnName(@"sym42")]
            public float Sym42 { get; set; }

            [ColumnName(@"sym43")]
            public float Sym43 { get; set; }

            [ColumnName(@"sym44")]
            public float Sym44 { get; set; }

            [ColumnName(@"sym45")]
            public float Sym45 { get; set; }

            [ColumnName(@"sym46")]
            public float Sym46 { get; set; }

            [ColumnName(@"sym47")]
            public float Sym47 { get; set; }

            [ColumnName(@"sym48")]
            public float Sym48 { get; set; }

            [ColumnName(@"sym49")]
            public float Sym49 { get; set; }

            [ColumnName(@"sym50")]
            public float Sym50 { get; set; }

            [ColumnName(@"sym51")]
            public float Sym51 { get; set; }

            [ColumnName(@"sym52")]
            public float Sym52 { get; set; }

            [ColumnName(@"sym53")]
            public float Sym53 { get; set; }

            [ColumnName(@"sym54")]
            public float Sym54 { get; set; }

            [ColumnName(@"sym55")]
            public float Sym55 { get; set; }

            [ColumnName(@"sym56")]
            public float Sym56 { get; set; }

            [ColumnName(@"sym57")]
            public float Sym57 { get; set; }

            [ColumnName(@"sym58")]
            public float Sym58 { get; set; }

            [ColumnName(@"sym59")]
            public float Sym59 { get; set; }

            [ColumnName(@"sym60")]
            public float Sym60 { get; set; }

            [ColumnName(@"sym61")]
            public float Sym61 { get; set; }

            [ColumnName(@"sym62")]
            public float Sym62 { get; set; }

            [ColumnName(@"sym63")]
            public float Sym63 { get; set; }

            [ColumnName(@"sym64")]
            public float Sym64 { get; set; }

            [ColumnName(@"sym65")]
            public float Sym65 { get; set; }

            [ColumnName(@"sym66")]
            public float Sym66 { get; set; }

            [ColumnName(@"sym67")]
            public float Sym67 { get; set; }

            [ColumnName(@"sym68")]
            public float Sym68 { get; set; }

            [ColumnName(@"sym69")]
            public float Sym69 { get; set; }

            [ColumnName(@"sym70")]
            public float Sym70 { get; set; }

            [ColumnName(@"sym71")]
            public float Sym71 { get; set; }

            [ColumnName(@"sym72")]
            public float Sym72 { get; set; }

            [ColumnName(@"sym73")]
            public float Sym73 { get; set; }

            [ColumnName(@"sym74")]
            public float Sym74 { get; set; }

            [ColumnName(@"sym75")]
            public float Sym75 { get; set; }

            [ColumnName(@"sym76")]
            public float Sym76 { get; set; }

            [ColumnName(@"sym77")]
            public float Sym77 { get; set; }

            [ColumnName(@"sym78")]
            public float Sym78 { get; set; }

            [ColumnName(@"sym79")]
            public float Sym79 { get; set; }

            [ColumnName(@"sym80")]
            public float Sym80 { get; set; }

            [ColumnName(@"sym81")]
            public float Sym81 { get; set; }

            [ColumnName(@"sym82")]
            public float Sym82 { get; set; }

            [ColumnName(@"sym83")]
            public float Sym83 { get; set; }

            [ColumnName(@"sym84")]
            public float Sym84 { get; set; }

            [ColumnName(@"sym85")]
            public float Sym85 { get; set; }

            [ColumnName(@"sym86")]
            public float Sym86 { get; set; }

            [ColumnName(@"sym87")]
            public float Sym87 { get; set; }

            [ColumnName(@"sym88")]
            public float Sym88 { get; set; }

            [ColumnName(@"sym89")]
            public float Sym89 { get; set; }

            [ColumnName(@"sym90")]
            public float Sym90 { get; set; }

            [ColumnName(@"sym91")]
            public float Sym91 { get; set; }

            [ColumnName(@"sym92")]
            public float Sym92 { get; set; }

            [ColumnName(@"sym93")]
            public float Sym93 { get; set; }

            [ColumnName(@"sym94")]
            public float Sym94 { get; set; }

            [ColumnName(@"sym95")]
            public float Sym95 { get; set; }

            [ColumnName(@"sym96")]
            public float Sym96 { get; set; }

            [ColumnName(@"sym97")]
            public float Sym97 { get; set; }

            [ColumnName(@"sym98")]
            public float Sym98 { get; set; }

            [ColumnName(@"sym99")]
            public float Sym99 { get; set; }

            [ColumnName(@"sym100")]
            public float Sym100 { get; set; }

            [ColumnName(@"sym101")]
            public float Sym101 { get; set; }

            [ColumnName(@"sym102")]
            public float Sym102 { get; set; }

            [ColumnName(@"sym103")]
            public float Sym103 { get; set; }

            [ColumnName(@"sym104")]
            public float Sym104 { get; set; }

            [ColumnName(@"sym105")]
            public float Sym105 { get; set; }

            [ColumnName(@"sym106")]
            public float Sym106 { get; set; }

            [ColumnName(@"sym107")]
            public float Sym107 { get; set; }

            [ColumnName(@"sym108")]
            public float Sym108 { get; set; }

            [ColumnName(@"sym109")]
            public float Sym109 { get; set; }

            [ColumnName(@"sym110")]
            public float Sym110 { get; set; }

            [ColumnName(@"sym111")]
            public float Sym111 { get; set; }

            [ColumnName(@"sym112")]
            public float Sym112 { get; set; }

            [ColumnName(@"sym113")]
            public float Sym113 { get; set; }

            [ColumnName(@"sym114")]
            public float Sym114 { get; set; }

            [ColumnName(@"sym115")]
            public float Sym115 { get; set; }

            [ColumnName(@"sym116")]
            public float Sym116 { get; set; }

            [ColumnName(@"sym117")]
            public float Sym117 { get; set; }

            [ColumnName(@"sym118")]
            public float Sym118 { get; set; }

            [ColumnName(@"sym119")]
            public float Sym119 { get; set; }

            [ColumnName(@"sym120")]
            public float Sym120 { get; set; }

            [ColumnName(@"sym121")]
            public float Sym121 { get; set; }

            [ColumnName(@"sym122")]
            public float Sym122 { get; set; }

            [ColumnName(@"sym123")]
            public float Sym123 { get; set; }

            [ColumnName(@"sym124")]
            public float Sym124 { get; set; }

            [ColumnName(@"sym125")]
            public float Sym125 { get; set; }

            [ColumnName(@"sym126")]
            public float Sym126 { get; set; }

            [ColumnName(@"sym127")]
            public float Sym127 { get; set; }

            [ColumnName(@"sym128")]
            public float Sym128 { get; set; }

            [ColumnName(@"sym129")]
            public float Sym129 { get; set; }

            [ColumnName(@"sym130")]
            public float Sym130 { get; set; }

            [ColumnName(@"sym131")]
            public float Sym131 { get; set; }

            [ColumnName(@"sym132")]
            public float Sym132 { get; set; }

            [ColumnName(@"sym133")]
            public float Sym133 { get; set; }

            [ColumnName(@"sym134")]
            public float Sym134 { get; set; }

            [ColumnName(@"sym135")]
            public float Sym135 { get; set; }

            [ColumnName(@"sym136")]
            public float Sym136 { get; set; }

            [ColumnName(@"sym137")]
            public float Sym137 { get; set; }

            [ColumnName(@"sym138")]
            public float Sym138 { get; set; }

            [ColumnName(@"sym139")]
            public float Sym139 { get; set; }

            [ColumnName(@"sym140")]
            public float Sym140 { get; set; }

            [ColumnName(@"sym141")]
            public float Sym141 { get; set; }

            [ColumnName(@"sym142")]
            public float Sym142 { get; set; }

            [ColumnName(@"sym143")]
            public float Sym143 { get; set; }

            [ColumnName(@"sym144")]
            public float Sym144 { get; set; }

            [ColumnName(@"sym145")]
            public float Sym145 { get; set; }

            [ColumnName(@"sym146")]
            public float Sym146 { get; set; }

            [ColumnName(@"sym147")]
            public float Sym147 { get; set; }

            [ColumnName(@"sym148")]
            public float Sym148 { get; set; }

            [ColumnName(@"sym149")]
            public float Sym149 { get; set; }

            [ColumnName(@"sym150")]
            public float Sym150 { get; set; }

            [ColumnName(@"sym151")]
            public float Sym151 { get; set; }

            [ColumnName(@"sym152")]
            public float Sym152 { get; set; }

            [ColumnName(@"sym153")]
            public float Sym153 { get; set; }

            [ColumnName(@"sym154")]
            public float Sym154 { get; set; }

            [ColumnName(@"sym155")]
            public float Sym155 { get; set; }

            [ColumnName(@"sym156")]
            public float Sym156 { get; set; }

            [ColumnName(@"sym157")]
            public float Sym157 { get; set; }

            [ColumnName(@"sym158")]
            public float Sym158 { get; set; }

            [ColumnName(@"sym159")]
            public float Sym159 { get; set; }

            [ColumnName(@"sym160")]
            public float Sym160 { get; set; }

            [ColumnName(@"sym161")]
            public float Sym161 { get; set; }

            [ColumnName(@"sym162")]
            public float Sym162 { get; set; }

            [ColumnName(@"sym163")]
            public float Sym163 { get; set; }

            [ColumnName(@"sym164")]
            public float Sym164 { get; set; }

            [ColumnName(@"sym165")]
            public float Sym165 { get; set; }

            [ColumnName(@"sym166")]
            public float Sym166 { get; set; }

            [ColumnName(@"sym167")]
            public float Sym167 { get; set; }

            [ColumnName(@"sym168")]
            public float Sym168 { get; set; }

            [ColumnName(@"sym169")]
            public float Sym169 { get; set; }

            [ColumnName(@"sym170")]
            public float Sym170 { get; set; }

            [ColumnName(@"sym171")]
            public float Sym171 { get; set; }

            [ColumnName(@"sym172")]
            public float Sym172 { get; set; }

            [ColumnName(@"sym173")]
            public float Sym173 { get; set; }

            [ColumnName(@"sym174")]
            public float Sym174 { get; set; }

            [ColumnName(@"sym175")]
            public float Sym175 { get; set; }

            [ColumnName(@"sym176")]
            public float Sym176 { get; set; }

            [ColumnName(@"sym177")]
            public float Sym177 { get; set; }

            [ColumnName(@"sym178")]
            public float Sym178 { get; set; }

            [ColumnName(@"sym179")]
            public float Sym179 { get; set; }

            [ColumnName(@"sym180")]
            public float Sym180 { get; set; }

            [ColumnName(@"sym181")]
            public float Sym181 { get; set; }

            [ColumnName(@"sym182")]
            public float Sym182 { get; set; }

            [ColumnName(@"sym183")]
            public float Sym183 { get; set; }

            [ColumnName(@"sym184")]
            public float Sym184 { get; set; }

            [ColumnName(@"sym185")]
            public float Sym185 { get; set; }

            [ColumnName(@"sym186")]
            public float Sym186 { get; set; }

            [ColumnName(@"sym187")]
            public float Sym187 { get; set; }

            [ColumnName(@"sym188")]
            public float Sym188 { get; set; }

            [ColumnName(@"sym189")]
            public float Sym189 { get; set; }

            [ColumnName(@"sym190")]
            public float Sym190 { get; set; }

            [ColumnName(@"sym191")]
            public float Sym191 { get; set; }

            [ColumnName(@"sym192")]
            public float Sym192 { get; set; }

            [ColumnName(@"sym193")]
            public float Sym193 { get; set; }

            [ColumnName(@"sym194")]
            public float Sym194 { get; set; }

            [ColumnName(@"sym195")]
            public float Sym195 { get; set; }

            [ColumnName(@"sym196")]
            public float Sym196 { get; set; }

            [ColumnName(@"sym197")]
            public float Sym197 { get; set; }

            [ColumnName(@"sym198")]
            public float Sym198 { get; set; }

            [ColumnName(@"sym199")]
            public float Sym199 { get; set; }

            [ColumnName(@"sym200")]
            public float Sym200 { get; set; }

            [ColumnName(@"sym201")]
            public float Sym201 { get; set; }

            [ColumnName(@"sym202")]
            public float Sym202 { get; set; }

            [ColumnName(@"sym203")]
            public float Sym203 { get; set; }

            [ColumnName(@"sym204")]
            public float Sym204 { get; set; }

            [ColumnName(@"sym205")]
            public float Sym205 { get; set; }

            [ColumnName(@"sym206")]
            public float Sym206 { get; set; }

            [ColumnName(@"sym207")]
            public float Sym207 { get; set; }

            [ColumnName(@"sym208")]
            public float Sym208 { get; set; }

            [ColumnName(@"sym209")]
            public float Sym209 { get; set; }

            [ColumnName(@"sym210")]
            public float Sym210 { get; set; }

            [ColumnName(@"sym211")]
            public float Sym211 { get; set; }

            [ColumnName(@"sym212")]
            public float Sym212 { get; set; }

            [ColumnName(@"sym213")]
            public float Sym213 { get; set; }

            [ColumnName(@"sym214")]
            public float Sym214 { get; set; }

            [ColumnName(@"sym215")]
            public float Sym215 { get; set; }

            [ColumnName(@"sym216")]
            public float Sym216 { get; set; }

            [ColumnName(@"sym217")]
            public float Sym217 { get; set; }

            [ColumnName(@"sym218")]
            public float Sym218 { get; set; }

            [ColumnName(@"sym219")]
            public float Sym219 { get; set; }

            [ColumnName(@"sym220")]
            public float Sym220 { get; set; }

            [ColumnName(@"sym221")]
            public float Sym221 { get; set; }

            [ColumnName(@"sym222")]
            public float Sym222 { get; set; }

            [ColumnName(@"sym223")]
            public float Sym223 { get; set; }

            [ColumnName(@"sym224")]
            public float Sym224 { get; set; }

            [ColumnName(@"sym225")]
            public float Sym225 { get; set; }

            [ColumnName(@"sym226")]
            public float Sym226 { get; set; }

            [ColumnName(@"Disease")]
            public uint Disease { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel1.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict scores for all possible labels.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            var result = predEngine.Predict(input);
            return GetSortedScoresWithLabels(result);
        }

        /// <summary>
        /// Map the unlabeled result score array to the predicted label names.
        /// </summary>
        /// <param name="result">Prediction to get the labeled scores from.</param>
        /// <returns>Ordered list of label and score.</returns>
        /// <exception cref="Exception"></exception>
        public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(ModelOutput result)
        {
            var unlabeledScores = result.Score;
            var labelNames = GetLabels(result);

            Dictionary<string, float> labledScores = new Dictionary<string, float>();
            for (int i = 0; i < labelNames.Count(); i++)
            {
                // Map the names to the predicted result score array
                var labelName = labelNames.ElementAt(i);
                labledScores.Add(labelName.ToString(), unlabeledScores[i]);
            }

            return labledScores.OrderByDescending(c => c.Value);
        }

        /// <summary>
        /// Get the ordered label names.
        /// </summary>
        /// <param name="result">Predicted result to get the labels from.</param>
        /// <returns>List of labels.</returns>
        /// <exception cref="Exception"></exception>
        private static IEnumerable<string> GetLabels(ModelOutput result)
        {
            var schema = PredictEngine.Value.OutputSchema;

            var labelColumn = schema.GetColumnOrNull("Disease");
            if (labelColumn == null)
            {
                throw new Exception("Disease column not found. Make sure the name searched for matches the name in the schema.");
            }

            // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value.
            var keyNames = new VBuffer<float>();
            labelColumn.Value.GetKeyValues(ref keyNames);
            return keyNames.DenseValues().Select(x => x.ToString());
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
